Пользователи и вещи
leliaOff/java-shareit pull request #1
Opened 2024-08-15 06:29 UTC by leliaOff

Добавлены функциональности: пользователи, вещи

2024-08-16 08:31 UTC, mikita95 requested changes
Все сделано просто отлично :) Оставил лишь пару рекомендаций по логированию

2024-08-16 08:31 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +            return Optional.empty();
Лучше было бы дополнительно залогировать ошибку, чтобы легче было разбираться в дальнейшем

2024-08-16 08:31 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/base/BaseRepository.java
> +        } catch (NullPointerException exception) {
Лучше было бы залогировать ошибку

2024-08-16 13:41 UTC, leliaOff commented
добавила логирование

2024-08-17 13:12 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-08-26 05:17 UTC, merged