Add bookings
leliaOff/java-shareit pull request #2
Opened 2024-09-02 08:48 UTC by leliaOff

2024-09-03 08:20 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь небольшие замечания

2024-09-03 08:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/base/helpers/DateTimeHelper.java
> +        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern(pattern, Locale.US);
Можно вынести в константы :)

2024-09-03 08:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
Эту аннотацию нужно осторожно использовать над сущностями hibernate, так как она генерирует методы toString и hashcode, что может привести к инициализации ленивых полей и циклическим вызовам

2024-09-03 08:20 UTC, mikita95 commented on src/main/resources/schema.sql
> +    user_id bigint not null constraint comments_users_id_fk references users,
Можно было бы добавить индексы на колонки, по которым часто выполняются запросы, так будет эффективнее

2024-09-03 08:47 UTC, leliaOff commented
исправлено

2024-09-04 08:52 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-09-04 09:11 UTC, merged